import { useState } from "react";
const API = import.meta.env.VITE_API_URL || "http://localhost:4000/api";
const fallbackCover = "https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg";

export function BookDetails({ book, onClose, onUpdated, onRemove, onUnauthorized }) {
  const [editing, setEditing] = useState(false); const [form, setForm] = useState(book); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); try { const token = localStorage.getItem("library_token"); if (!token) return onUnauthorized(); const response = await fetch(`${API}/books/${book.id}`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(form) }); if (response.status === 401) return onUnauthorized(); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); onUpdated(payload.data); setEditing(false); } catch (err) { setError(err.message || "Could not update this book"); } finally { setSaving(false); } }
  return <div className="modal-backdrop"><section className="modal detail-modal" role="dialog" aria-modal="true" aria-label="Book details"><button className="icon-button close" onClick={onClose} aria-label="Close">×</button>{editing ? <form className="book-form" onSubmit={save}><p className="eyebrow">EDIT BOOK</p><h2>Edit details</h2><label>Book title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Author<input required value={form.author} onChange={(e) => setForm({ ...form, author: e.target.value })} /></label><div className="form-row"><label>Category<input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Want to read</option><option>Reading</option><option>Completed</option></select></label></div><label>Cover image URL<input type="url" value={form.coverUrl || ""} onChange={(e) => setForm({ ...form, coverUrl: e.target.value })} /></label>{error && <p className="error">{error}</p>}<div className="detail-actions"><button type="button" className="secondary" onClick={() => setEditing(false)}>Cancel</button><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></form> : <div className="detail-content"><img src={book.coverUrl || fallbackCover} alt={`Cover of ${book.title}`} onError={(e) => { e.currentTarget.src = fallbackCover; }} /><div><span className={`status ${book.status.toLowerCase().replaceAll(" ", "-")}`}>{book.status}</span><p className="eyebrow">{book.category}</p><h2>{book.title}</h2><p className="detail-author">by {book.author}</p><div className="detail-actions"><button className="secondary" onClick={() => setEditing(true)}>Edit details</button><button className="danger" onClick={() => onRemove(book)}>Delete</button></div></div></div>}</section></div>;
}
